### ISSUE TITLE
Network Display + Communication

### ISSUE THREAD

**Issue by kpet123** [kpet123/Network-Composition#1]
Find way to display pretty + dynamic network in html. 

Allow this to communicate and change based off messages to and from Networkx backend.

**Comment by kpet123** [comment]
Link to Google Sheet comparing different potential methods. Focusing on a few main factors: how graphics look, ease of animating a walk across network, and ease of integrating with networkx backend. 
Link: [https://observablehq.com/@nstrayer/a-graphical-experiment-of-exponential-spread](url)

**Comment by kaiser-dan** [comment]
Decided on Flask + D3 framework, initialized in flaskapp branch
