### ISSUE TITLE
Community Visualization

### ISSUE THREAD

**Issue by kpet123** [kpet123/Network-Composition#8]
Good source: [https://observablehq.com/@d3/force-directed-tree?collection=@d3/d3-force](url) that allows you to show hierarchical structure. Other approaches involve mapping colors to a 'community' parameter defined in each node.

**Comment by kaiser-dan** [comment]
Mechanisms added, need to select proper color scheme.

**Comment by kaiser-dan** [comment]
Colorschemes discussed, will finalize tomorrow morning.
